export const siteCopy = {
  identity: {
    zh: "未命名档案",
    en: "UNTITLED ARCHIVE",
    markLabel: "临时站点标记",
  },
  navigation: [
    { href: "/", zh: "入口", en: "INDEX" },
    { href: "/characters", zh: "角色", en: "CHARACTER" },
    { href: "/world", zh: "世界", en: "WORLD" },
    { href: "/archive", zh: "档案", en: "ARCHIVE" },
    { href: "/gallery", zh: "图像", en: "GALLERY" },
  ],
  theme: {
    toLight: "切换为浅色模式",
    toDark: "切换为深色模式",
  },
  home: {
    issue: "ISSUE 00",
    classification: "ORIGINAL CHARACTER / PRIVATE ARCHIVE",
    chapter: "OPENING FILE",
    waiting: "等待第一份角色资料",
    waitingEn: "PORTRAIT & RECORD PENDING",
    imagePlaceholder: "临时场景美术",
    imagePlaceholderEn: "TEMPORARY ENVIRONMENT ART",
    mediaLabel: "肖像资料待补充",
    mediaNote: "角色页面将使用独立肖像与对应焦点设置",
    scroll: "向下探索",
    futureCharacterArt: "此处将替换为正式角色美术",
    featuredIntro: "第一位角色的姓名、肖像与人物资料尚未录入。正式图片加入后，画面会重新按角色视线与构图重排。",
    worldTitle: "世界尚未被完整记录",
    worldIntro: "角色、地点、事件与私人档案将从不同入口逐渐显现。现在先保留它们之间的空间与叙事关系。",
    explore: "探索站点内容",
    portals: [
      { href: "/world", zh: "世界", en: "WORLD" },
      { href: "/archive", zh: "档案", en: "ARCHIVE" },
      { href: "/gallery", zh: "图像", en: "GALLERY" },
    ],
    backToTop: "回到顶部",
    viewCharacters: "进入角色目录",
    viewCharactersEn: "ENTER CHARACTER INDEX",
    footerIndex: "ARCHIVE / 000—001",
    footerState: "INITIAL RECORD",
  },
  worldAtlas: {
    eyebrow: "WORLD RECORD / EXPLORATION PLATE",
    title: "世界观测图",
    intro: "移动到城市节点，地图会沿真实世界轮廓聚焦。角落中的观测卡记录当地时间与此刻天气。",
    mapLabel: "包含主要城市节点的交互式世界地图",
    hint: "悬停、聚焦或点击城市 · HOVER / FOCUS / TAP",
    footer: "ROBINSON PROJECTION · LIVE CITY OBSERVATORY",
    weatherLoading: "正在接收气象记录",
    weatherUnavailable: "实时天气暂不可用",
    weatherSource: "WEATHER · OPEN-METEO",
    localTime: "当地时间",
    weather: "当前天气",
    temperature: "温度",
    wind: "风速",
    coordinates: "坐标",
    cities: [
      { code: "TOR", name: "多伦多", en: "TORONTO", country: "加拿大", countryEn: "CANADA", latitude: 43.6532, longitude: -79.3832, timeZone: "America/Toronto" },
      { code: "NYC", name: "纽约", en: "NEW YORK", country: "美国", countryEn: "UNITED STATES", latitude: 40.7128, longitude: -74.006, timeZone: "America/New_York" },
      { code: "MEX", name: "墨西哥城", en: "MEXICO CITY", country: "墨西哥", countryEn: "MEXICO", latitude: 19.4326, longitude: -99.1332, timeZone: "America/Mexico_City" },
      { code: "SAO", name: "圣保罗", en: "SÃO PAULO", country: "巴西", countryEn: "BRAZIL", latitude: -23.5505, longitude: -46.6333, timeZone: "America/Sao_Paulo" },
      { code: "LON", name: "伦敦", en: "LONDON", country: "英国", countryEn: "UNITED KINGDOM", latitude: 51.5072, longitude: -0.1276, timeZone: "Europe/London" },
      { code: "PAR", name: "巴黎", en: "PARIS", country: "法国", countryEn: "FRANCE", latitude: 48.8566, longitude: 2.3522, timeZone: "Europe/Paris" },
      { code: "CAI", name: "开罗", en: "CAIRO", country: "埃及", countryEn: "EGYPT", latitude: 30.0444, longitude: 31.2357, timeZone: "Africa/Cairo" },
      { code: "DXB", name: "迪拜", en: "DUBAI", country: "阿联酋", countryEn: "UNITED ARAB EMIRATES", latitude: 25.2048, longitude: 55.2708, timeZone: "Asia/Dubai" },
      { code: "SIN", name: "新加坡", en: "SINGAPORE", country: "新加坡", countryEn: "SINGAPORE", latitude: 1.3521, longitude: 103.8198, timeZone: "Asia/Singapore" },
      { code: "SHA", name: "上海", en: "SHANGHAI", country: "中国", countryEn: "CHINA", latitude: 31.2304, longitude: 121.4737, timeZone: "Asia/Shanghai" },
      { code: "TYO", name: "东京", en: "TOKYO", country: "日本", countryEn: "JAPAN", latitude: 35.6762, longitude: 139.6503, timeZone: "Asia/Tokyo" },
      { code: "SYD", name: "悉尼", en: "SYDNEY", country: "澳大利亚", countryEn: "AUSTRALIA", latitude: -33.8688, longitude: 151.2093, timeZone: "Australia/Sydney" },
    ],
  },
  routes: {
    characters: {
      index: "01",
      eyebrow: "CHARACTER INDEX",
      title: "角色目录",
      intro: "角色将从同一套资料结构进入这里，而不是各自拥有一套写死的页面。",
      empty: "其余角色档案尚未公开。",
    },
    world: {
      index: "02",
      eyebrow: "WORLD RECORD",
      title: "世界",
      intro: "地区、组织、制度、地点与事件将在这里形成可进入的世界结构。",
      empty: "世界记录尚未归档。",
    },
    archive: {
      index: "03",
      eyebrow: "MEDIA ARCHIVE",
      title: "档案",
      intro: "每份记录将保留它原本的媒介语言：论文、简报、短信、新闻或私人笔记。",
      empty: "当前没有公开档案。",
    },
    gallery: {
      index: "04",
      eyebrow: "VISUAL MATERIAL",
      title: "图像",
      intro: "插画、概念、委托、CG、设计与模型将在这里按来源和时间组织。",
      empty: "第一张图像仍在等待入库。",
    },
  },
  common: {
    back: "返回",
    status: "状态",
    pending: "待补充",
    featured: "当前主档案",
    openRecord: "查看档案",
    profile: "人物记录",
    residenceUnavailable: "该角色目前没有开放的居所记录。",
  },
  characterPage: {
    showcase: {
      eyebrow: "CHARACTER SHOWCASE",
      title: "形象展示",
      intro: "立绘、头像、草图与片段会在这里逐步出现。不同画幅保留各自的观看距离。",
      pending: "影像待补",
      slots: [
        { zh: "立绘", en: "FULL BODY", code: "FIG. 01" },
        { zh: "立绘", en: "FULL BODY", code: "FIG. 02" },
        { zh: "立绘", en: "FULL BODY", code: "FIG. 03" },
        { zh: "头像", en: "PORTRAIT", code: "HEAD. 01" },
        { zh: "横图", en: "LANDSCAPE", code: "SCENE. 01" },
      ],
    },
    archive: {
      eyebrow: "CHARACTER DOSSIER",
      title: "人物档案",
      intro: "文字记录、人物经历与关系资料将集中收录于档案中。",
      pending: "文字资料待录入",
      open: "进入人物档案",
      openEn: "OPEN DOSSIER",
    },
  },
  residence: {
    eyebrow: "RESIDENCE",
    title: "居所",
    intro: "从窗口向里看。她会按照时间与随机事件，在房间、工作地点和日常事务之间自行行动。",
    watchHint: "拖动视角或使用控制键 · DRAG OR USE CONTROLS",
    ambientOn: "播放环境音乐",
    ambientOff: "关闭环境音乐",
    ambientEn: "AMBIENT",
    audioUnavailable: "声音没能开启。",
    greet: "敲敲窗",
    greetEn: "SAY HI",
    defaultReply: "敲敲窗，看看她有没有回应。",
    activities: {
      sleep: { zh: "已经睡下", en: "ASLEEP", mood: "(－_－) zzZ" },
      work: { zh: "在家办公", en: "WORKING AT HOME", mood: "( •̀ᴗ•́ )و" },
      read: { zh: "正在看文献", en: "READING", mood: "( ｡•̀ᴗ-)✧" },
      cat: { zh: "正在逗猫", en: "WITH THE CAT", mood: "ฅ^•ﻌ•^ฅ" },
      idle: { zh: "在房间里休息", en: "AT HOME", mood: "( ˘͈ ᵕ ˘͈ )" },
      away: { zh: "外出中", en: "AWAY", mood: "⌂  · · ·" },
    },
    weather: {
      "clear-day": { zh: "晴", en: "CLEAR DAY" },
      "clear-night": { zh: "晴夜", en: "CLEAR NIGHT" },
      cloudy: { zh: "多云", en: "CLOUDY" },
      rain: { zh: "下雨", en: "RAIN" },
      storm: { zh: "雷雨", en: "THUNDERSTORM" },
      rainbow: { zh: "淡彩虹", en: "PALE RAINBOW" },
    },
    replies: {
      sleep: [
        "睡着了。",
        "明早见。",
      ],
      work: [
        "看见你了。",
        "稍等一下。",
      ],
      read: [
        "你好。",
        "嗯？你好。",
      ],
      cat: [
        "猫先回头了。",
        "它替我问好。",
      ],
      idle: [
        "你好呀。",
        "看见你了。",
      ],
      away: [
        "不在家。",
        "晚点回来。",
      ],
    },
  },
} as const;

export type RouteCopyKey = keyof typeof siteCopy.routes;
