export const siteCopy = {
  identity: {
    zh: "未命名档案",
    en: "UNTITLED ARCHIVE",
    markLabel: "临时站点标记",
  },
  navigation: [
    { href: "/", zh: "入口", en: "INDEX" },
    { href: "/characters", zh: "角色", en: "CHARACTER" },
    { href: "/world", zh: "世界", en: "WORLD" },
    { href: "/archive", zh: "档案", en: "ARCHIVE" },
    { href: "/gallery", zh: "图像", en: "GALLERY" },
  ],
  theme: {
    toLight: "切换为浅色模式",
    toDark: "切换为深色模式",
  },
  home: {
    issue: "ISSUE 00",
    classification: "ORIGINAL CHARACTER / PRIVATE ARCHIVE",
    chapter: "OPENING FILE",
    waiting: "等待第一份角色资料",
    waitingEn: "PORTRAIT & RECORD PENDING",
    imagePlaceholder: "临时场景美术",
    imagePlaceholderEn: "TEMPORARY ENVIRONMENT ART",
    mediaLabel: "肖像资料待补充",
    mediaNote: "角色页面将使用独立肖像与对应焦点设置",
    scroll: "向下探索",
    futureCharacterArt: "此处将替换为正式角色美术",
    featuredIntro: "第一位角色的姓名、肖像与人物资料尚未录入。正式图片加入后，画面会重新按角色视线与构图重排。",
    worldTitle: "世界尚未被完整记录",
    worldIntro: "角色、地点、事件与私人档案将从不同入口逐渐显现。现在先保留它们之间的空间与叙事关系。",
    explore: "探索站点内容",
    portals: [
      { href: "/world", zh: "世界", en: "WORLD" },
      { href: "/archive", zh: "档案", en: "ARCHIVE" },
      { href: "/gallery", zh: "图像", en: "GALLERY" },
    ],
    backToTop: "回到顶部",
    viewCharacters: "进入角色目录",
    viewCharactersEn: "ENTER CHARACTER INDEX",
    footerIndex: "ARCHIVE / 000—001",
    footerState: "INITIAL RECORD",
  },
  routes: {
    characters: {
      index: "01",
      eyebrow: "CHARACTER INDEX",
      title: "角色目录",
      intro: "角色将从同一套资料结构进入这里，而不是各自拥有一套写死的页面。",
      empty: "其余角色档案尚未公开。",
    },
    world: {
      index: "02",
      eyebrow: "WORLD RECORD",
      title: "世界",
      intro: "地区、组织、制度、地点与事件将在这里形成可进入的世界结构。",
      empty: "世界记录尚未归档。",
    },
    archive: {
      index: "03",
      eyebrow: "MEDIA ARCHIVE",
      title: "档案",
      intro: "每份记录将保留它原本的媒介语言：论文、简报、短信、新闻或私人笔记。",
      empty: "当前没有公开档案。",
    },
    gallery: {
      index: "04",
      eyebrow: "VISUAL MATERIAL",
      title: "图像",
      intro: "插画、概念、委托、CG、设计与模型将在这里按来源和时间组织。",
      empty: "第一张图像仍在等待入库。",
    },
  },
  common: {
    back: "返回",
    status: "状态",
    pending: "待补充",
    featured: "当前主档案",
    openRecord: "查看档案",
    profile: "人物记录",
    residenceUnavailable: "该角色目前没有开放的居所记录。",
  },
} as const;

export type RouteCopyKey = keyof typeof siteCopy.routes;
